#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  8 17:26:50 2022

@author: joseph
"""


x=0
import pandas


scgs=pandas.read_excel("/Users/joseph/Desktop/gene lists:papers for RNA seq differentation/MGI GO membrane organisation and membrane biogenesis.xlsx")
cilialist1=scgs["Symbol"].tolist()
cilialist2=[]
for name in cilialist1:
    if name not in cilialist2:
        cilialist2.append(name)
cells=pandas.DataFrame()
cells[0]=cilialist2
cells.to_excel('GI GO membrane organisation and membrane biogenesis reduced.xlsx')
print(cilialist2)

